### ISSUE TITLE
.copy() capability in all objects

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#63]
A basic copy method would be useful. i.e object2 = object1.copy(). The copy library can be used to do this.

AC:
* Create a copy (as a new instance) of an existing object using a call object.copy().
* Preserve lazy loading

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL Been trying to figure out how and when lazy loading ends and whether using copy.copy() would load the data to memory. Brace yourself for a very dry couple of paragraphs. Please read though because I might be very far off the mark....

According to the docs for xarray.open_dataset [(link),](http://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html) `cache = True` by default *unless* `chunks` is specified, in which case data is put into DASK arrays and `cache = False`. So if DASK is used, caching is off by default. However, in the COAsT `load()` functions, `chunks = None` by default, which is also the default for xarray.open_dataset... so I don't think DASK is used by default, and therefore `cache=True`.

This can be seen by invoking `OBJ.dataset.variable_name.variable._data`, or e.g. `NEMO.dataset.nav_lon.variable._data`. As it stands this returns a `MemoryCachedArray`, which according to this [stackoverflow page](https://stackoverflow.com/questions/45622581/how-can-i-check-whether-a-python-xarray-dataset-dataarray-object-is-loaded-into) means the data *is* cached. If `cache=False` in COAsT.load(), then you instead get a `copyOnWriteArray`, which *isn't* cached. If you *do* specify `chunk`, e.g. `chunks={}` or using an `int`/`dict`, then you get a dask.array object, which I guess is also lazy loaded.

*Anyway*, doing a shallow copy of a NEMO/DOMAIN/OBSERVATION object using `copy.copy()` preserves `copyOnWriteArray` or `MemoryCachedArray`. So  I think it preserves the lazy loading. Doing a deep copy loads in the data.

When it comes to adding/multiplying the data by scalars:  Neither `MemoryCachedArray` nor `copyOnWriteArray` are preserved by multiplication, however the `dask.array` *is*.

**Comment by anwiseNOCL** [comment]
@jpolton @davbyr Seems quite confusing to me!

[Here](http://xarray.pydata.org/en/stable/io.html) it states that:
"Data is _always_ loaded lazily from netCDF files. You can manipulate, slice and subset Dataset and DataArray objects, and no array values are loaded into memory until you try to perform some sort of actual computation."

The following from the cache bit in the xarray.open_dataset doc is not quite clear to me:
"If True, cache data loaded from the underlying datastore in memory as NumPy arrays when accessed". 

So this might just mean that when cache is set to True, lazy loading is still used but when you access the underlying data of a variable it will be cached so that it is not reloaded every time you try to access it. If cache is set to False, then everytime you try to access that variable data, that data will be loaded from disk, not memory. The MemoryCachedArray could therefore just be the datatype needed in order to cache arrays, but doesn't imply that they are cached.

But I don't know that for sure !

**Comment by jpolton** [comment]
@davbyr @anwiseNOCL - it is confusing and I suspect our code doesn't apply things consistently...

My pragmatic solution would be to get a big dataset. Open Activity Monitor and look at Memory. Load the data and try out a few options and see what happens to the machine's memory and test the hypotheses. Having digested the evidence I might then reach out to stack overflow

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton  - Ok curiosity got the better of me. The following little test does seem to suggest that on this occasion stackoverflow might actually be wrong...

tester = xr.open_dataset( PATH_TO_DOMAIN_CFG, cache=True )
tester.e2v.variable._data  # outputs type MemoryCachedArray but it appears to be empty 
tester.e2v.values  # Access the data as numpy array
tester.e2v.variable._data  # outputs type MemoryCachedArray but now it contains data, i.e. it was lazy loaded, now its cached into memory

So seems cache=True does just load the data once it is directly accessed (not when it is sliced or subsetted though, according to the documentation)

**Comment by davbyr** [comment]
@anwiseNOCL You're right. Right now, COAsT creates empty `MemoryCachedArray` things by default, unless chunks is specified. The moment this is accessed (in ways other than basic indexing), it is no longer empty. Either way, whatever form it is in seems to be preserved by copying.

Quick note, doing any kind of operation with a whole variable also seems to load in the data, so:
```
a = nemo_var.nav_lon
b = a + 10
```
But if you do the same thing by indexing, it doesn't:
```
b = a[:] + 10
```
Can also avoid loading in data during a routine by copying the necessary variables at the start using copy.copy() and working with them.
