### ISSUE TITLE
Model Superclass

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#67]
A class in between COAsT and NEMO to allow for a more general handling approach of model data. The inheritance flow would be COAsT -> MODEL -> NEMO. MODEL would contain model specific routines, NEMO would contain NEMO specific variables and possibly routine. COAsT could be treated as a more general utility class.

AC:
COAsT -> MODEL -> NEMO exists and NEMO can be loaded and manipulated successfully.

**Comment by jpolton** [comment]
@davbyr How should the DOMAIN class fit it to this structure?

**Comment by davbyr** [comment]
@jpolton It's a good question and I'm not sure. I came to do this issue on Friday, but got a bit stuck with this problem.

The option with the least classes is just to put all the data and methods, domain and variable, inside the MODEL class. I think we discussed that this is OK unless you need to use one domain for multiple variable objects, in which case this becomes cumbersome if the data starts getting loaded in.

Maybe there could be a MODEL_VAR and MODEL_DOM pair of classes. Then there can be NEMO/FVCOM etc subclasses of these. MODEL_VAR could contain a pointer to its corresponding MODEL_DOM class or something...

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton I think this make sense, though we are assuming that all ocean models can easily be separated into model output and domain. Just a thought, but perhaps MODEL_OUT (as in output) could replace MODEL_VAR, because essentially being output is what identifies it as different from DOMAIN, which is a model input. Or perhaps MODEL_DATA?

If we are going down this design route does it mean that all classes need to designed in this way? For example if I create a TRANSECT base class, I now need to create a derived NEMO_TRANSECT class, with the implementation specific to NEMO?

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL That's a good point. I imagine most models with static co-ordinates can be boiled down to the same format in the end though? The file layout might differ, so load methods might differ, but the end objects could be comparable.

Yeah I agree MODEL_OUT or MODEL_DATA would be more accurate. Don't have a preference either way though.

I don't know exactly what the TRANSECT class would contain/do, but maybe there could just be a single transect class but the methods used to create it from data/domain would be model specific, if needed? Or if every model class contains standardised variables called `longitude`, `latitude` etc, this might not be needed. It would be nice to not have *everything* separated into `NEMO_` and `FVCOM_` objects, so I reckon the more that can be put in the higher superclasses the better.

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton Not sure if you started on this Dave but, thinking about this a bit more, just thought i'd put this out there. A clean approach would be to create subpackages for the different models (basically just sub-directories in coast). This doesn't really change anything but it is a nice way to prevent us having to prefix stuff with the model name e.g.

coast/
-init.py
-COAsT.py
-Obs...py
-Alt..py
-NEMO/
--NEMO.py (could call this Model_data, Model_out or even just diagnostics.py)
--DOMAIN.py
--any other nemo specific modules we might want to prevent NEMO.py getting too long
-FVCOM/
--FVCOM.py (or follow whatever convention used for NEMO)
..and so on

This has quite a few advantages i think: opens up a model specific namespace, clearer structure (in my opinion), easy to split development between different models, retains the ability to inherit as before and to put common functionality in COAsT.py or in new modules at that level but also offers an easy way to split up NEMO.py (or whatever we will call it) if it gets too long and unwieldy while retaining a NEMO specific namespace.

**Comment by davbyr** [comment]
@anwiseNOCL @jpolton Fiddled a little but didnt settle on anything. I think that sounds like could work. So when working with the package, you could create a NEMO or FVCOM object and then access NEMO.DOMAIN.whatever or NEMO.DATA.whatever?

e.g.
```
nemo_data = NEMO.DATA.load(fn_data)
nemo_dom = NEMO.DOMAIN.load(fn_dom)
```

In this structure, are NEMO/FVCOM etc still subclasses of COAsT? So load can still live in COAsT.

**Comment by davbyr** [comment]
@anwiseNOCL Sorry, I think I might have misunderstood what you meant.. Could you give a quick example?

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton  So NEMO and FVCOM are just subpackages (directory names) not classes, it doesn't affect the current class structure, the Domain and Data classes can still inherit from COAsT in the same way they currently do. 
So an example might be:
```
nemo = coast.NEMO.Data() 
nemo.load(fn_data)
nemo.do_something_using_this_data_method()
nemodom = coast.NEMO.Domain()
nemodom.load(fn_domain)
```
```
fvcom = coast.FVCOM.Data() 
fvcom.load(fn_data)
fvcom.do_something_using_this_data_method()
fvcomdom = coast.FVCOM.Domain()
fvcomdom.load(fn_domain)
```
You could still create that extra class between COAsT and Data, but on reflection I just wasn't sure if it's needed. Probably easier to discuss over VC. I think this is probably quite an important step to get right.

Also, without wishing to rock the boat too much. There should really be an option to load the data or pass in an xarray dataset when the Data and Domain objects are created, rather than doing it without 
 an additional step. :)

**Comment by davbyr** [comment]
@anwiseNOCL Sounds good. Would definitely be good to discuss more over VC though.

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL Just been thinking on this a little bit: I think it would be good to adopt both a Model superclass object structure and a model specific directory structure.

Having a model superclass would make the whole package much more scaleable than only sorting things by directory. It is the MODEL class (and any children) that should adhere to the naming conventions that we have set out. Then anything that can be applied directly to that format would go in MODEL. This allows for all new models (FVCOM, ROMS) to be added quickly and use a large amount of the same codebase as previously. Simply copying data across for these shared routines is probably a bad idea, especially as the package grows larger.

Examples of what would be in MODEL:

1. Generic load routine. This should be overridden in each child of the class however.
2. Subsetting routines. We know the data structure so this should be in one place.
3. Plotting routines
4. Anything that uses longitude/latitude/time/depth (if not in its own class)

So a MODEL class would resemble what COAsT is now, but with any future additions that can be generalised. I'd say as much as possible should be generalised. Features that have not been written to be used in general (TRANSECT) would then go in model specific directories directories. Directories could look like:

-coast
--NEMO
--FVCOM
--GENERAL

In coast would live parent classes, e.g. MODEL, OBSERVATION, COAsT etc. Things like ALTIMETRY could have their own directory too maybe, although I'm not sure.

Key point: Using object inheritance is important for scaleability of the package and should be used as much as possible. Copying large amounts of code also means maintaining large amounts of similar code.

I might be repeating a lot of the same stuff that we have already discussed, but thought I should get these thoughts on the ticket.

**Comment by jpolton** [comment]
A key advantage of @davbyr suggestion would be that a new model class would have a clean requirement: Namely to load the data into an xr.DataSet with {latitude, longitude, depth, time} as coordinates and {temperature, salinity, this and that} as variables. Then all the methods in model superclass should work. Extra effort would be required to map model specific code (e.g TRANSECT.py). A downside of this approach is that it introduces an extra level of complexity / abstraction for the non OO programmers.

@anwiseNOCL alternative of copying NEMO.py --> FVCOM.py and fixing it probably is a same amount of work if we are diligent to ensure that everything goes into COAsT.py that can go into COAsT.py
Subsequent copying NEMO/TRANSECT.py --> FVCOM/TRANSECT.py, etc and fixing it would be similar amounts of effort.

Dave raises a good point about inheritance and keeping the code tidy. How well that happens probably depends more on the developers and the codebase custodians being vigilant to stop too much model specific code being (lazily) written, rather than whether or not a superclass is used.

Assuming I've understood both arguments correctly, on balance I'm marginally in favour of the extra level of complexity, with the superclass, since it might encourage better programming.

**Comment by anwiseNOCL** [comment]
@davbyr @jpolton I agree, this is a good idea, I think it was probably the original motivation behind the COAsT class? Couple of things: 

1. Will there be anything left inside the COAsT class? i.e is there functionality common to all Model, Observation and other Stats Classes that currently inherit from it?
2. Probably it is not an issue because methods in the Model class can be overridden, but models like FVCOM have unstructured grids I think, does that affect anything? 
3. Just to be clear, the directory and file structure (subpackages and modules) I was talking about, is about namespaces, not class structures. e.g. coast.Nemo.Transect, coast.Roms.Transect is better than coast.nemo_transect and coast.roms_transect I think.
