### ISSUE TITLE
Pass xarray to COAsT package

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#73]
User might already have a loaded dataset. Let them pass that to the COAsT package.

Method: pass a dictionary of model variables with the expected name mappings, along with an xarray object. E.g.

```
variable_mapping = {standard_name : weird_var_name,....}
nemoObj = coast.NEMO()
nemoObj.load_dataset(dataset, variable_mapping)
```

Then inside COAsT

```
def load_dataset(dataset: xarray.dataset, variable_mapping: dictionary):
   dataset.rename(variable_mapping)
   self.dataset = dataset
```

AC: 
* the old load routine works as before.
* preserves lazy loading
* Does stuff and has a unit test

**Comment by anwiseNOCL** [comment]
@jpolton  @davbyr  Just to expand on this:

In essence what we have created is a wrapper around an xarray dataset with added methods to do the useful diagnostics on this dataset (a composition object).

Currently the user creates a COAsT/NEMO object
`nemoObj = coast.NEMO()`
then loads some data
`nemoObj.load("PATH_TO_FILE.nc")`
which assigns an xarray dataset to the nemoObj attribute i.e
self.dataset = xarray_dataset_loaded_from_netCDF_file (this is inherited from COAsT)

It would be nice to be able to do this more explicitly with optional arguments
`nemoObj = coast.NEMO(dataset: xarraydataset, variablemapping: dictionary)`
or even
```
nemoObj = coast.NEMO()
nemoObj.load_dataset(dataset: xarraydataset, variablemapping: dictionary)
```
(Personally i think data or the file path should be passed in when the object is created since the object does nothing without data, but not a big deal.)

Anyway, the problem of using standard variable names throughout the package is common to all approaches, not just when passing in an xarray dataset explicitly.

For example, if you try to load the standard variable names by
`nemoObj.set_command_variables()`
then it will try to do it with code like:
`self.ssh = self.dataset.sossheig`
If the netCDF file that was loaded by the user didn't use 'sossheig' for the sea surface height variable then this will raise an error, or break something later! The user has no way to tell the nemoObj what variable naming convention is used in the netCDF file. 

Whether we pass in an dataset or file path the user should also have the option to pass in a variable mapping dictionary. [Even better, xarray has this functionality built-in and allows you to rename variables and dimensions using a dictionary](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.rename.html)
`xarray.Dataset.rename`

Users of this package in the future could use all sorts of weird names for their variables (or use reanalysis data with weird variable names) so I think we need to be able to handle this rather than forcing people to start renaming variables in their netCDF files. Did anyone use the Iris package? I'm sure there is a similar issue in that where they force you to use standard metadata conventions.

**Comment by jpolton** [comment]
@anwiseNOCL I am happy to adopt this structure for loading file and / or datasets.
This seems like a fairly non-invasive restructuring of how NEMO.load would be implemented.
My concern would be around keeping an eye on time: what we have works (though has room for improvement), but no one will help us do the "novel science" elements...
Maybe we could develop the idea and save it for the next Sprint? (It we could just do it, if when well-defined, is could be identified as small enough)

**Comment by jpolton** [comment]
@thogar-computer (cc @anwiseNOCL ) What was the rationale for the two step process:
nemoObj = coast.NEMO()
nemoObj.load("PATH_TO_FILE.nc")
Since one never goes without the other? Is it some kind of OOP style Thing?

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL Sounds good Ant. 

So if I want to use longitude/latitude/time inside a CRPS routine, I get them directly from the NEMO.dataset variable using the variable mapping dictionary instead of doing it via an intermediate variable.? I.E. 
```NEMO.dataset[ map_dict['longitude'] ]```
using 
```map_dict = {'longitude' : 'nav_lon', ...}```
Is this correct or am I still misunderstanding?

**Comment by anwiseNOCL** [comment]
@jpolton 
True, we don't have time to spend changing things that work. I can just add in a .load_dataset() method very quickly that will not affect any other code and gives the option.

@davbyr 
I was thinking that it shouldn't affect existing code at all. I imagine it will go something like
```
variable_mapping = {standard_name : weird_var_name,....}
nemoObj = coast.NEMO()
nemoObj.load_dataset(dataset, variable_mapping)
```
Then inside COAsT
```
def load_dataset(dataset: xarray.dataset, variable_mapping: dictionary):
   dataset.rename(variable_mapping)
   self.dataset = dataset
```
Then everything should just work as is. You can use the nemoObj.dataset.variable or nemoObj.variable (once set_command_variables has been executed).

**Comment by davbyr** [comment]
@anwiseNOCL Ahh I see, sounds great.

**Comment by jpolton** [comment]
> @anwiseNOCL Ahh I see, sounds great.

@anwiseNOCL , Agreed - sounds great. I've updated the opening comment accordingly. Edit further if necessary.
